name: "2 - Shift Traffic to Canary"
on:
  workflow_dispatch:

jobs:
  shift-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ops Repository
        uses: actions/checkout@v4
        with:
          repository: PixelCodeeee/arroyo-ops
          path: ops
          token: ${{ secrets.GH_PAT }}

      - name: Set Redis Announcement (via SSH)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_IAP_CREDENTIALS }}

      - name: Setup GCloud (IAP)
        uses: google-github-actions/setup-gcloud@v2

      - name: Broadcast Maintenance Message
        run: |
          gcloud compute ssh joshualuna@private-backend-vm \
            --project=beta-prime-489121 \
            --zone=us-central1-a \
            --tunnel-through-iap \
            --command="sudo docker exec microservices-redis-shared-1 redis-cli set maintenance:announcement:stable 'La sesión terminará pronto debido a una actualización' EX 900" || true

      - name: Authenticate GCP (Load Balancer API)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Evaluate Manifest & Shift Traffic Independently
        run: |
          FE_READY=$(jq -r '.frontend.status' ops/manifests/canary.json)
          BE_READY=$(jq -r '.backend.status' ops/manifests/canary.json)

          if [ "$BE_READY" == "ready" ]; then
            echo "🚀 Backend is ready. Shifting Backend traffic to 10%."
            gcloud compute backend-services update arroyo-backend-svc \
              --project=beta-prime-489121 --global \
              --custom-request-headers="x-frontend-version: canary" \
              --custom-response-header="Set-Cookie: X-Frontend-Version=canary; Path=/; Max-Age=3600" \
              --canary-weight=10
          fi

          if [ "$FE_READY" == "ready" ]; then
            echo "🚀 Frontend is ready. Shifting Frontend traffic to 10%."
            gcloud compute backend-services update arroyo-frontend-svc \
              --project=beta-prime-489121 --global \
              --custom-request-headers="x-frontend-version: canary" \
              --custom-response-header="Set-Cookie: X-Frontend-Version=canary; Path=/; Max-Age=3600" \
              --canary-weight=10
          fi

      - name: Wait for Metrics
        run: sleep 300